name: ee408ass1
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py27_0
  - cffi=1.12.2=py27h2e261b9_1
  - cudatoolkit=9.0=h13b8566_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py27ha843d7b_0
  - mkl_random=1.0.2=py27hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py27h6bb024c_1
  - numpy=1.16.2=py27h7e9f1db_0
  - numpy-base=1.16.2=py27hde5b4d6_0
  - olefile=0.46=py27_0
  - openssl=1.1.1b=h7b6447c_1
  - pillow=5.4.1=py27h34e0f95_0
  - pip=19.0.3=py27_0
  - pycparser=2.19=py27_0
  - python=2.7.15=h9bab390_6
  - readline=7.0=h7b6447c_5
  - setuptools=40.8.0=py27_0
  - six=1.12.0=py27_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.1=py27_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.0.1=py2.7_cuda9.0.176_cudnn7.4.2_2
  - torchvision=0.2.2=py_3
prefix: /home/jack/anaconda2/envs/ee408ass1

